-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 21:43:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regions` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `regio_club_fk_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `region_club_fk`
    FOREIGN KEY (`region_id`)
    REFERENCES `regions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disciplines` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions` (
  `id` INT NOT NULL,
  `name` VARCHAR(800) NOT NULL,
  `date_competition` DATE NOT NULL,
  `lieux` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `equipe` INT(1) NOT NULL DEFAULT 0,
  `archive` INT(1) NOT NULL DEFAULT 1,
  `date_desactivation` DATE NULL,
  `document` TEXT NULL,
  `categorie_id` INT(11) NOT NULL,
  `discipline_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `discipline_competition_fk_idx` (`discipline_id` ASC) VISIBLE,
  INDEX `categorie_competition_fk_idx` (`categorie_id` ASC) VISIBLE,
  CONSTRAINT `discipline_competition_fk`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `categorie_competition_fk`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profils` (
  `id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `fonction` VARCHAR(255) NULL,
  `active` INT(1) NOT NULL,
  `lastlogin` DATETIME NULL,
  `profil_id` INT(11) NOT NULL,
  `club_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC, `prenom` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `profil_user_fk_idx` (`profil_id` ASC) VISIBLE,
  INDEX `club_user_fk_idx` (`club_id` ASC) VISIBLE,
  CONSTRAINT `club_user_fk`
    FOREIGN KEY (`club_id`)
    REFERENCES `clubs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `profil_user_fk`
    FOREIGN KEY (`profil_id`)
    REFERENCES `profils` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiques` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `user_id` INT(11) NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `user_historique_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_historique_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grades` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licencies` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `ddn` DATE NOT NULL,
  `sexe` VARCHAR(1) NOT NULL,
  `numero_licence` VARCHAR(45) NULL,
  `grade_id` INT(11) NOT NULL,
  `club_id` INT(11) NOT NULL,
  `discipline_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `club_licencie_fk_idx` (`club_id` ASC) VISIBLE,
  INDEX `grade_licencie_fk_idx` (`grade_id` ASC) VISIBLE,
  INDEX `discipline_licencie_fk_idx` (`discipline_id` ASC) VISIBLE,
  CONSTRAINT `club_licencie_fk`
    FOREIGN KEY (`club_id`)
    REFERENCES `clubs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_licencie_fk`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discipline_licencie_fk`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inscription_competitions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inscription_competitions` (
  `id` INT NOT NULL,
  `commentaire` TEXT NULL,
  `surclassement` INT(1) NOT NULL DEFAULT 0,
  `autorisation` INT(1) NOT NULL DEFAULT 0,
  `certificat` INT(1) NOT NULL DEFAULT 0,
  `competition_id` INT(11) NOT NULL,
  `licencie_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `competition_inscription_fk_idx` (`competition_id` ASC) VISIBLE,
  INDEX `user_cpt_inscription_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `licencie_cpt_inscription_idx` (`licencie_id` ASC) VISIBLE,
  CONSTRAINT `competition_inscription_fk`
    FOREIGN KEY (`competition_id`)
    REFERENCES `competitions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_cpt_inscription_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `licencie_cpt_inscription`
    FOREIGN KEY (`licencie_id`)
    REFERENCES `licencies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `passages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passages` (
  `id` INT NOT NULL,
  `name` VARCHAR(800) NOT NULL,
  `date_competition` DATE NOT NULL,
  `lieux` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `archive` INT(1) NOT NULL DEFAULT 1,
  `date_desactivation` DATE NULL,
  `document` TEXT NULL,
  `discipline_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `discipline_passage_fk_idx` (`discipline_id` ASC) VISIBLE,
  CONSTRAINT `passage_competition_fk`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inscription_passages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inscription_passages` (
  `id` INT NOT NULL,
  `commentaire` TEXT NULL,
  `passage_id` INT(11) NOT NULL,
  `licencie_id` INT(11) NOT NULL,
  `grade_presente_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `passage_inscripyion_fk_idx` (`passage_id` ASC) VISIBLE,
  INDEX `licencie_inscription_fk_idx` (`licencie_id` ASC) VISIBLE,
  INDEX `grade_inscription_fk_idx` (`grade_presente_id` ASC) VISIBLE,
  INDEX `user_inscription_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `passage_inscription_fk`
    FOREIGN KEY (`passage_id`)
    REFERENCES `passages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `licencie_inscription_fk`
    FOREIGN KEY (`licencie_id`)
    REFERENCES `licencies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_inscription_fk`
    FOREIGN KEY (`grade_presente_id`)
    REFERENCES `grades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_inscription_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parametres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parametres` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `value` TEXT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inscription_administratif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inscription_administratif` (
  `id` INT NOT NULL,
  `arbitre` INT(1) NOT NULL DEFAULT 0,
  `commissaire` INT(1) NOT NULL DEFAULT 0,
  `jury` INT(1) NOT NULL,
  `licencie_id` INT(11) NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `licencie_adm_inscription_idx` (`licencie_id` ASC) VISIBLE,
  INDEX `user_adm_inscription_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `licencie_adm_inscription`
    FOREIGN KEY (`licencie_id`)
    REFERENCES `licencies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_adm_inscription`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
